### ISSUE TITLE
Rendered Manifests contain a resource that already exists

### ISSUE THREAD

**Issue by Vad1mo** [zloeber/helm-namespace#5]
I created the namespace with this plugin but after some additions to the helmfile this error appears. 
Sidenote, I didn't touch the namespace section.

```yaml

releases:
  - name: loki-namespace
    chart: zloeber/namespace
    values:
      - namespaces:
          - loki
        labels:
          name: loki
```

` Failed to render chart: exit status 1: Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: loki, existing_kind: /v1, Kind=Namespace, new_kind: /v1, Kind=Namespace`

**Comment by Vad1mo** [comment]
got it. I accidently removed the namespace where the helmchart resides.


```yaml
releases:
  - name: loki
    namespace: loki
    chart: loki/loki-stack
    needs:
      - default/loki-namespace
  - name: loki-namespace
    chart: zloeber/namespace
    namespace: default
    values:
      - namespaces:
          - loki
        labels:
          name: loki
```
